model: spanbert-large-cased
data_dir: /usr0/home/gis/data/tacred/data/json
output_dir:
eval_per_epoch: 10
max_seq_length: 128
negative_label: "no_relation"
# What to run
do_train: True
train_mode: random_sorted # choices: ['random', 'sorted', 'random_sorted']
do_eval: True
eval_test: True

do_lower_case: False
feature_mode: ner
train_batch_size: 16
eval_batch_size: 32
eval_metric: f1
learning_rate: 0.00002
num_train_epochs: 10
warmup_proportion: .1
no_cuda: False
seed: 42
gradient_accumulation_steps: 2
fp16: True
loss_scale: 0

with_jrrelp: True
jrrelp_lambda: .1
without_observed: False
without_verification: False
exclude_no_relation: False
